### PR TITLE
String concatnation +=

### PR DESCRIPTION
**Pull request by landonfox00**

### CODE REVIEW

**Comment by davecparker** [comment]
Shouldn't the error on line 947 be:
"%s cannot be applied to type %s"
instead of 
"%s can only be applied to type %s"

Also your test code doesn't show evidence of cases what would have generated this error.

I'll show you how to put correct and error tests in the automated test and you can try them there.

**Comment by landonfox00** [comment]
Finished this pull request. Let me know if you'd like more testing in the automated testing.

**Comment by davecparker** [comment]
Looks like you need to undo your changes to
Desktop/Error Test/main.lua

**Comment by landonfox00** [comment]
My bad, thanks for catching that. Should be good now

**Pull request merged**
